### ISSUE TITLE
部署完成后，flanneld 启动失败，

### ISSUE THREAD

**Issue by charles-liming** [zhangguanzhang/Kubernetes-ansible#1]

**Comment by zhangguanzhang** [comment]
加下我微信，下载个tw13，我远程帮你看看

**Comment by zhangguanzhang** [comment]
hostname在kubelet只认小写，改写flanneld的system渲染为小写
```
Environment=NODE_NAME={{ nodename | lower }}
```

**Comment by zhy123345** [comment]
怎么总是给我发邮件啊------------------ 原始邮件 ------------------
发件人: "zhangguanzhang"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午3:29
收件人: "zhangguanzhang/Kubernetes-ansible"<Kubernetes-ansible@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [zhangguanzhang/Kubernetes-ansible] 部署完成后，flanneld 启动失败， (#1)



hostname在kubelet只认小写，改写flanneld的system渲染为小写
 Environment=NODE_NAME={{ nodename | lower }}  
&mdash;

**Comment by zhangguanzhang** [comment]
应该是设置的邮件提醒
