### ISSUE TITLE
最后coredns一直在Creating，求助，多谢

### ISSUE THREAD

**Issue by herotan** [zhangguanzhang/Kubernetes-ansible#10]
Events:
  Type     Reason                  Age                    From                    Message
  ----     ------                  ----                   ----                    -------
  Normal   Scheduled               46m                    default-scheduler       Successfully assigned kube-system/coredns-58b448b5d9-hhlxt to 158.143.70.21
  Warning  FailedCreatePodSandBox  33m (x19 over 46m)     kubelet, 158.143.70.21  Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "gcr.azk8s.cn/google_containers/pause-amd64:3.1": Error response from daemon: Get http://gcr.azk8s.cn/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  FailedCreatePodSandBox  33m                    kubelet, 158.143.70.21  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "aa57fe03f3b22c54a17783490252498e67bcdd7bb4c226c7055df91625d4551c" network for pod "coredns-58b448b5d9-hhlxt": NetworkPlugin cni failed to set up pod "coredns-58b448b5d9-hhlxt_kube-system" network: failed to find plugin "loopback" in path [/opt/cni/bin], failed to clean up sandbox container "aa57fe03f3b22c54a17783490252498e67bcdd7bb4c226c7055df91625d4551c" network for pod "coredns-58b448b5d9-hhlxt": NetworkPlugin cni failed to teardown pod "coredns-58b448b5d9-hhlxt_kube-system" network: failed to find plugin "portmap" in path [/opt/cni/bin]]
  Normal   SandboxChanged          11m (x104 over 33m)    kubelet, 158.143.70.21  Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          3m9s (x26 over 8m43s)  kubelet, 158.143.70.21  Pod sandbox changed, it will be killed and re-created.
[root@node1 .kube]# kubectl get pod -n kube-system
NAME                              READY   STATUS              RESTARTS   AGE
coredns-58b448b5d9-hhlxt          0/1     ContainerCreating   0          47m
coredns-58b448b5d9-mptg5          0/1     ContainerCreating   0          47m
metrics-server-86c9cbd9f5-zblwz   0/1     ContainerCreating   0          47m
[root@node1 .kube]#

**Comment by zhangguanzhang** [comment]
你的cni文件没有在剧本目录，你在每个node上
```
ls -l /opt/cni/bin
```
看下，应该是没有cni解压开的文件

**Comment by herotan** [comment]
已经单独安装 了一次cni 的RPM包，复制到这目录 OK了。多谢
