### ISSUE TITLE
云上环境不支持VIP，针对SLB要怎样部署HA？

### ISSUE THREAD

**Issue by zhaiyuzhen** [zhangguanzhang/Kubernetes-ansible#15]
看过 https://zhangguanzhang.github.io/2019/03/11/k8s-ha/ ，但是没得要领。

**Comment by zhangguanzhang** [comment]
可以local proxy

**Comment by zhaiyuzhen** [comment]
> 可以local proxy

针对这个ansible部署脚本，需要怎样修改？

**Comment by zhangguanzhang** [comment]
你在每个node上起个haproxy就行了，可以实体服务，也可以staticPod，然后每个访问apiserver的vip改成127.0.0.1

**Comment by zhaiyuzhen** [comment]
好的，谢谢。
