### ISSUE TITLE
需要改进

### ISSUE THREAD

**Issue by xubinfeng** [zhangguanzhang/Kubernetes-ansible#16]
你的连接搞成这样，又依靠分支分支搞，实在没办法给你推送新的东西，本来想修改点东西给到你。

**Comment by zhangguanzhang** [comment]
直接submodule上去提交就行了

**Comment by zhangguanzhang** [comment]
而且版本更新后官方不维护了，所以没必要所有版本都融合在一起里面加一堆判断

**Comment by xubinfeng** [comment]
这个做好了对学习k8s和ansible都是非常不错的实例；你这样引用我不太会提交，我提交不上去，单独的项目连接会好点

**Comment by zhangguanzhang** [comment]
你需要改哪个地方，我教你怎么提交吧
