### ISSUE TITLE
请教kubelet.crt证书的有效期，thanks!!!

### ISSUE THREAD

**Issue by herotan** [zhangguanzhang/Kubernetes-ansible#18]
请教：

为何kubelet 的证书就一年，ansible安装的参数文件配置的是10年
/etc/kubernetes/pki/kubelet.crt
notBefore=Aug 20 11:52:15 2020 GMT
notAfter=Aug 20 11:52:15 2021 GMT

其它证书没问题，还有个admin.crt是做什么用的？有时也是一年。

/etc/kubernetes/pki/front-proxy-client.crt
notBefore=Aug 20 12:47:08 2020 GMT
notAfter=Jun  5 12:47:08 2294 GMT
/etc/kubernetes/pki/kube-scheduler.crt
notBefore=Aug 20 12:47:09 2020 GMT
notAfter=Jun  5 12:47:09 2294 GMT
/etc/kubernetes/pki/sa.crt
notBefore=Aug 20 12:47:09 2020 GMT
notAfter=Jun  5 12:47:09 2294 GMT
/etc/kubernetes/pki/admin.crt
notBefore=Aug 20 12:47:10 2020 GMT
notAfter=Jun  5 12:47:10 2294 GMT

**Comment by zhangguanzhang** [comment]
bootstrap会轮训

**Comment by herotan** [comment]
收到，谢谢，到期后不用手动干预吧，包括重启kubelet之类的。

**Comment by zhangguanzhang** [comment]
你把kubelet-current那个证书的软链删了，然后重启kubelet就知道了

**Comment by herotan** [comment]
测试成功，明白了，多谢
