### ISSUE TITLE
请教：三个master有两个flanneld启动不起来，帮忙指导下。

### ISSUE THREAD

**Issue by herotan** [zhangguanzhang/Kubernetes-ansible#19]
Searching for interface using 10.249.21.198
Using interface with name eth0 and address 10.249.21.198
Using 10.249.21.198 as external address
Waiting 10m0s for node controller to sync
Starting kube subnet manager
Node controller sync successful
Created subnet manager: Kubernetes Subnet Manager - 10.249.21.198
Installing signal handlers
Found network config - Backend type: vxlan
 VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
 VXLAN device already exists
 Returning existing device
**Error registering network: failed to acquire lease: node "10.249.21.198" p**
Stopping shutdownHandler...
Start healthz server on 10.249.21.198:8471

**Comment by zhangguanzhang** [comment]
```
journalctl -xe -u flanneld > /dev/stdout
```
把完整日志粘贴

**Comment by herotan** [comment]
搞定了&nbsp; 是我pod cidr掩码设置大了，node多，分配不够。我就直接改了引用podcidr变量的几个文件，重启服务好了。


kuberlet证书快一年了，需要手动处理吗？还是会自动更新？


多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月6日(周日) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangguanzhang/Kubernetes-ansible] 请教：三个master有两个flanneld启动不起来，帮忙指导下。 (#19)




 journalctl -xe -u flanneld &gt; /dev/stdout  
把完整日志粘贴

**Comment by zhangguanzhang** [comment]
你可以把那个使用的文件改名，然后重启下kubelet看看会不会生成新的，理论上证书过期或者不见了会重新申请的
