### ISSUE TITLE
group master 大小写错误

### ISSUE THREAD

**Issue by lee-cn** [zhangguanzhang/Kubernetes-ansible#3]
Kubernetes-ansible/roles/master/tasks/main.yml

when: inventory_hostname in groups['Master']

Kubernetes-ansible/roles/master/templates/kube-apiserver.service.j2

--apiserver-count={{ groups['Master'] | length }} \

**Comment by zhangguanzhang** [comment]
没错，兼容后续扩master的
[Master]
master
newMaster
