### ISSUE TITLE
把group_vars/all.yml中docker版本改成最新的18.09后，安装失败

### ISSUE THREAD

**Issue by kevinzu007** [zhangguanzhang/Kubernetes-ansible#5]
vim  group_vars/all.yml
version: '18.06'
改成version: '18.09' 后出现以下错误：
---------------------------------------
fatal: [192.168.11.172]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce-3:18.09.7-3.el7' found available, installed or updated", "rc": 126, "results": ["No package match
ing 'docker-ce-3:18.09.7-3.el7' found available, installed or updated"]}

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/Kubernetes-ansible/blob/master/roles/docker/tasks/centos.yml#L5
```
yum list --showduplicates 'docker-ce' | awk  '/'{{ docker.version }}'.*el/{if($2~":"){sub(/[^:]+:/,"",$2)};a=$2}END{print a}'
```
刚改了下添加逻辑判断，你改下这行一样再试试

**Comment by kevinzu007** [comment]
恩，可以了
