### ISSUE TITLE
flanneld error

### ISSUE THREAD

**Issue by ddy4633** [zhangguanzhang/Kubernetes-ansible#7]
Nov 26 13:41:09 master01 sshd[16199]: pam_unix(sshd:session): session opened for user root by (uid=0)
Nov 26 13:41:10 master01 kubelet[6675]: E1126 13:41:10.001237    6675 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://172.16.128.24
Nov 26 13:41:10 master01 kubelet[6675]: E1126 13:41:10.004250    6675 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://172.16.128.240:84
Nov 26 13:41:10 master01 kubelet[6675]: E1126 13:41:10.009359    6675 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://172.16.128
Nov 26 13:41:10 master01 kubelet[6675]: E1126 13:41:10.010773    6675 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://172.16.128.24
Nov 26 13:41:10 master01 kubelet[6675]: E1126 13:41:10.013051    6675 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://172.16.128.240:8443/
Nov 26 13:41:10 master01 kubelet[6675]: E1126 13:41:10.344709    6675 controller.go:125] failed to ensure node lease exists, will retry in 7s, error: Get https://172.16.128.240:8443/apis/coor
Nov 26 13:41:10 master01 kube-apiserver[2256]: E1126 13:41:10.411097    2256 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: e
Nov 26 13:41:10 master01 flanneld[15541]: E1126 13:41:10.828927   15541 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Unauthorized

**Comment by ddy4633** [comment]
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
Restart=always
RestartSec=5
KillMode=process

Environment=NODE_NAME=master02
ExecStart=/usr/local/bin/flanneld \
  --kube-subnet-mgr=true \
  --kubeconfig-file=/etc/kubernetes/flanneld.kubeconfig \
  --ip-masq=true \
  --iface=eth0 \
  --public-ip 172.16.128.21 \
  --healthz-ip 172.16.128.21 \
  --healthz-port 8471 \
  --v=0

[Install]
WantedBy=multi-user.target

**Comment by zhangguanzhang** [comment]
tls步骤重新执行
